from app import db
from datetime import datetime

class Supplier(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    contact_person = db.Column(db.String(100))
    phone = db.Column(db.String(20))
    email = db.Column(db.String(100))
    gstin = db.Column(db.String(15))
    address = db.Column(db.Text)
    city = db.Column(db.String(50))
    state = db.Column(db.String(50))
    pin_code = db.Column(db.String(10))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class Item(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.String(50), unique=True)
    name = db.Column(db.String(100), nullable=False)
    description = db.Column(db.Text)
    category = db.Column(db.String(50))
    hsn_code = db.Column(db.String(10))
    unit = db.Column(db.String(20), default='PCS')
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class PurchaseBill(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    bill_number = db.Column(db.String(50), unique=True, nullable=False)
    supplier_id = db.Column(db.Integer, db.ForeignKey('supplier.id'), nullable=False)
    bill_date = db.Column(db.Date, nullable=False)
    due_date = db.Column(db.Date)
    reference_number = db.Column(db.String(100))
    payment_terms = db.Column(db.String(50))
    subtotal = db.Column(db.Numeric(12, 2), nullable=False)
    total_discount = db.Column(db.Numeric(12, 2), default=0.00)
    taxable_amount = db.Column(db.Numeric(12, 2), nullable=False)
    cgst_amount = db.Column(db.Numeric(12, 2), default=0.00)
    sgst_amount = db.Column(db.Numeric(12, 2), default=0.00)
    igst_amount = db.Column(db.Numeric(12, 2), default=0.00)
    shipping_charges = db.Column(db.Numeric(12, 2), default=0.00)
    round_off = db.Column(db.Numeric(12, 2), default=0.00)
    grand_total = db.Column(db.Numeric(12, 2), nullable=False)
    shipping_info = db.Column(db.Text)
    notes = db.Column(db.Text)
    status = db.Column(db.String(20), default='draft')
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    supplier = db.relationship('Supplier', backref='purchase_bills')
    items = db.relationship('PurchaseBillItem', backref='purchase_bill')

class PurchaseBillItem(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    bill_id = db.Column(db.Integer, db.ForeignKey('purchase_bill.id'), nullable=False)
    item_id = db.Column(db.Integer, db.ForeignKey('item.id'))
    name = db.Column(db.String(100), nullable=False)
    description = db.Column(db.Text)
    quantity = db.Column(db.Numeric(10, 3), nullable=False)
    unit = db.Column(db.String(20), default='PCS')
    purchase_price = db.Column(db.Numeric(12, 2), nullable=False)
    discount_percent = db.Column(db.Numeric(5, 2), default=0.00)
    discount_amount = db.Column(db.Numeric(12, 2), default=0.00)
    taxable_value = db.Column(db.Numeric(12, 2), nullable=False)
    gst_rate = db.Column(db.Numeric(5, 2), default=0.00)
    cgst_amount = db.Column(db.Numeric(12, 2), default=0.00)
    sgst_amount = db.Column(db.Numeric(12, 2), default=0.00)
    igst_amount = db.Column(db.Numeric(12, 2), default=0.00)
    total_amount = db.Column(db.Numeric(12, 2), nullable=False)
    hsn_code = db.Column(db.String(10))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    item = db.relationship('Item')